apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"   # apply after the Operator

resources:
  - secret-root-creds.yaml
  - secret-config.yaml

helmCharts:
  - name: tenant
    repo: https://operator.min.io
    version: 7.1.1
    releaseName: wisp-tenant
    namespace: minio
    includeCRDs: false
    valuesInline:
      tenant:
        name: wisp
        pools:
          - name: pool-0            # <-- REQUIRED
            servers: 1
            volumesPerServer: 1
            size: 10Gi
            storageClassName: standard   # adjust to your cluster
        exposeServices:
          minio: true
          console: true
        configuration:
          name: wisp-minio-env
        configSecret:
          name: wisp-minio-env
          existingSecret: true
        credsSecret:
          name: wisp-minio-root-creds
      buckets:
        - name: wisp-media

