apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: wisp-minio-root-creds
    literals:
      - accesskey=minioadmin
      - secretkey=minioadmin123

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "1.9"
    
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"   # apply after the Operator

resources:
  - secret-root-creds.yaml
  # - secret-config.yaml

helmCharts:
  - name: tenant
    repo: https://operator.min.io
    version: 7.1.1
    releaseName: wisp-tenant
    namespace: minio
    includeCRDs: false
    valuesInline:
      tenant:
        name: wisp
        pools:
          - name: pool-0
            servers: 1
            volumesPerServer: 1
            size: 10Gi
            storageClassName: standard
        exposeServices:
          minio: true
          console: true
        requestAutoCert: true
        # ↓ use ONLY this; do NOT set 'configuration:'
        configSecret:
          name: wisp-minio-root-creds
          existingSecret: true

      buckets:
        - name: wisp-media


