apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - namespace.yaml

helmCharts:
  - name: nginx-ingress
    repo: oci://ghcr.io/nginx/charts
    version: 2.3.0
    releaseName: nginx-ingress
    namespace: ingress-nginx
    valuesInline:
      controller:
        ingressClassResource:
          name: f5-nginx
          enabled: true
          default: false
          controllerValue: nginx.org/ingress-controller




