apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgadmin
resources:
  - namespace.yaml

helmCharts:
  - name: pgadmin4
    repo: https://helm.runix.net
    version: 1.50.0
    releaseName: pgadmin
    namespace: pgadmin
    valuesInline:
      env:
        email: "admin@dev.local"
        password: "admin1234"
      serverDefinitions:
        enabled: true
        # MUST be a multiline string with JSON fragment of servers
        servers: |-
          "1": {
            "Name": "Wisp-Postgres",
            "Group": "Wisp",
            "Host": "postgres-postgresql.postgres.svc.cluster.local",
            "Port": 5432,
            "MaintenanceDB": "wispdb",
            "Username": "wisp",
            "SSLMode": "prefer"
          }
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: f5-nginx
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        hosts:
          - host: pgadmin.MINIKUBE_IP.nip.io   # replaced in dev overlay
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - pgadmin.MINIKUBE_IP.nip.io
            secretName: pgadmin-tls
