apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  - applicationset.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
