apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisp-backend
  namespace: wisp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisp-backend
  template:
    metadata:
      labels:
        app: wisp-backend
    spec:
      containers:
        - name: app
          image: ghcr.io/sraza0098/wisp-backend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-postgresql.postgres.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: wisp
            - name: DB_PASSWORD
              value: wisp123
            - name: DB_NAME
              value: wispdb
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
