apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisp-backend
  namespace: wisp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisp-backend
  template:
    metadata:
      labels:
        app: wisp-backend
    spec:
      containers:
        - name: app
          image: ghcr.io/sraza0098/wisp-backend:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              value: dev-secret-please-change   # dev only; move to Secret later
          envFrom:
            - secretRef:
                name: wisp-backend-db
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
