apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: true
      startupAPICheck:
        enabled: false
      global:
        leaderElection:
          namespace: cert-manager 
