apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis
resources:
  - namespace.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 19.5.5         # Redis 7, stable chart
    releaseName: redis
    namespace: redis
    valuesInline:
      architecture: standalone
      auth:
        enabled: false      # dev only (no password)
      master:
        service:
          type: ClusterIP
          ports:
            redis: 6379
