apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: operator
    repo: https://operator.min.io/
    version: 7.1.1          # pin to the version you saw
    releaseName: minio-operator
    namespace: minio
    includeCRDs: true
