apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 17.0.21
    releaseName: minio
    namespace: minio
    valuesInline:
      mode: standalone
      disableWebUI: false
      auth:
        rootUser: minioadmin
        rootPassword: minioadmin123
      defaultBuckets: wisp-media
      service:
        type: ClusterIP
